### PR TITLE
Add plugins by @MaxEtMoritz

### PR DESCRIPTION
**Pull request by modos189**

### CODE REVIEW

**Comment by MaxEtMoritz** [comment]
was reading about how to get my Plugins on here right when the PR popped up 🤣

**Comment by modos189** [comment]
@MaxEtMoritz It's funny) BTW, you use @icon and @icon64. Does it show up somewhere?

**Comment by MaxEtMoritz** [comment]
It does show up in TamperMonkey:

TM overview

TM details

**Comment by modos189** [comment]
@MaxEtMoritz Great! I'm going to add their display as well

**Pull request merged**
